server:
  port: 1010

spring:
  application:
    name: Registry


#eureka不论是DiscoveryClient还是Eureka Server默认都会向http://localhost:8761/eureka注册自己（register-with-eureka = true），并且从同样的地址去检索服务(fetch-registry: true)
#单节点的eureka server：
#  可以向一个eureka server(包括自己在内)注册自己（修改eureka.client.service-url.defaultZone的地址与目标eureka server 的地址一致）
#  或者，disable注册和检索服务列表的行为
eureka: #sd 配置
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka #自我注册
  server:
    enable-self-preservation: false
#    register-with-eureka: false     # false表示不向注册中心注册自己。
#    fetch-registry: false     # false表示自己端就是注册中心，职责就是维护服务实例，并不去检索服务

