server: #server配置
  port: 1011

eureka: #sd 配置
  instance:
    hostname: peer1.com
  client:
    service-url:
      defaultZone: http://peer2.com:1012/eureka #高可用，向peer2.com注册peer1, peer1将获得peer2的服务列表
  server:
    enable-self-preservation: false