server: #server配置
  port: 1012

spring:
  application:
    name: Registry

eureka: #sd 配置
  instance:
    hostname: peer2.com
  client:
    service-url:
      defaultZone: http://peer1.com:1011/eureka #高可用，向peer1.com注册peer2，peer2将获得peer1的服务列表
  server:
    enable-self-preservation: false