eureka: #sd 配置
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zpflyyer/spring-cloud-get-start.git
          search-paths: 'config/{application}'
          username: "15710165386@163.com"
          password: "@GITmy$2019"
          force-pull: true
#          手动访问config-server时需要先通过config-server的login接口鉴权
  security:
    user:
      name: config-user
      password: config-pwd
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud

#spring: #支持热部署
#  devtools:
#    restart:
#      enabled: true
server:
  port: 1020

management:
  endpoints:
    web:
      exposure:
        include: heath,info,refresh,bus-refresh
